set(TCV_HAS_PGSQL OFF)

if(VCPKG_INSTALLED_DIR AND VCPKG_TARGET_TRIPLET)
    set(_pq_wrapper "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/postgresql/vcpkg-cmake-wrapper.cmake")
    if(EXISTS "${_pq_wrapper}")
        message(STATUS "PostgreSQL wrapper present (vcpkg libpq installed), finding...")
        find_package(PostgreSQL QUIET)
        if(TARGET PostgreSQL::PostgreSQL)
            message(STATUS "PostgreSQL (libpq) FOUND — enabling TCV_HAS_PGSQL")
            set(TCV_HAS_PGSQL ON)
        else()
            message(STATUS "PostgreSQL (libpq) NOT found despite wrapper — TCV without PostgreSQL")
        endif()
    else()
        message(STATUS "PostgreSQL wrapper NOT present — skipping find_package (vcpkg libpq not installed)")
    endif()
else()
    message(STATUS "PostgreSQL: VCPKG_INSTALLED_DIR not set — skipping")
endif()

set(TCV_HAS_MYSQL OFF)

if(VCPKG_INSTALLED_DIR AND VCPKG_TARGET_TRIPLET)
    set(_ma_share "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/unofficial-libmariadb")
    if(EXISTS "${_ma_share}")
        message(STATUS "MySQL share present (vcpkg libmariadb installed), finding...")
        find_package(unofficial-libmariadb CONFIG QUIET)
        if(TARGET unofficial::libmariadb::libmariadb)
            message(STATUS "MySQL (libmariadb) FOUND — enabling TCV_HAS_MYSQL")
            set(TCV_HAS_MYSQL ON)
        else()
            message(STATUS "MySQL (libmariadb) NOT found despite share — TCV without MySQL")
        endif()
    else()
        message(STATUS "MySQL share NOT present — skipping find_package (vcpkg libmariadb not installed)")
    endif()
else()
    message(STATUS "MySQL: VCPKG_INSTALLED_DIR not set — skipping")
endif()

if(TCV_HAS_PGSQL)
    target_link_libraries(TingCloudVerifier PRIVATE PostgreSQL::PostgreSQL)
    target_compile_definitions(TingCloudVerifier PRIVATE TCV_HAS_PGSQL=1)
endif()

if(TCV_HAS_MYSQL)
    target_link_libraries(TingCloudVerifier PRIVATE unofficial::libmariadb::libmariadb)
    target_compile_definitions(TingCloudVerifier PRIVATE TCV_HAS_MYSQL=1)
endif()
