find_package(unofficial-libpq CONFIG QUIET)
if(TARGET unofficial::libpq::libpq)
    message(STATUS "PostgreSQL (libpq via vcpkg) FOUND — enabling TCV_HAS_PGSQL")
    set(TCV_HAS_PGSQL ON)
else()
    message(STATUS "PostgreSQL (libpq) NOT found — TCV will run WITHOUT PostgreSQL support")
    set(TCV_HAS_PGSQL OFF)
endif()

find_package(unofficial-libmariadb CONFIG QUIET)
if(TARGET unofficial::libmariadb::libmariadb)
    message(STATUS "MySQL (libmariadb) FOUND — enabling TCV_HAS_MYSQL")
    set(TCV_HAS_MYSQL ON)
else()
    message(STATUS "MySQL (libmariadb) NOT found — TCV will run WITHOUT MySQL support")
    set(TCV_HAS_MYSQL OFF)
endif()

if(TCV_HAS_PGSQL)
    target_link_libraries(TingCloudVerifier PRIVATE unofficial::libpq::libpq)
    target_compile_definitions(TingCloudVerifier PRIVATE TCV_HAS_PGSQL=1)
endif()

if(TCV_HAS_MYSQL)
    target_link_libraries(TingCloudVerifier PRIVATE unofficial::libmariadb::libmariadb)
    target_compile_definitions(TingCloudVerifier PRIVATE TCV_HAS_MYSQL=1)
endif()
