set(TCV_HAS_PGSQL OFF)

if(VCPKG_INSTALLED_DIR AND VCPKG_TARGET_TRIPLET)
    set(_pq_wrapper "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/postgresql/vcpkg-cmake-wrapper.cmake")
    if(EXISTS "${_pq_wrapper}")
        message(STATUS "PostgreSQL wrapper found: ${_pq_wrapper}")
    else()
        message(STATUS "PostgreSQL wrapper NOT found at ${_pq_wrapper} — vcpkg probably didn't install libpq")
    endif()
else()
    message(STATUS "PostgreSQL: VCPKG_INSTALLED_DIR=${VCPKG_INSTALLED_DIR}, VCPKG_TARGET_TRIPLET=${VCPKG_TARGET_TRIPLET}")
endif()

find_package(PostgreSQL QUIET)
if(TARGET PostgreSQL::PostgreSQL)
    message(STATUS "PostgreSQL (libpq) FOUND via find_package(PostgreSQL) — enabling TCV_HAS_PGSQL")
    set(TCV_HAS_PGSQL ON)
else()
    message(STATUS "PostgreSQL (libpq) NOT found — TCV will run WITHOUT PostgreSQL support")
    if(VCPKG_INSTALLED_DIR AND VCPKG_TARGET_TRIPLET)
        set(_pq_root "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
        message(STATUS "  vcpkg root = ${_pq_root}")
        if(EXISTS "${_pq_root}/include/libpq-fe.h")
            message(STATUS "  include EXISTS but library not found — check .so symlinks")
        else()
            message(STATUS "  include NOT FOUND — libpq port may not have been installed")
        endif()
    endif()
endif()

set(TCV_HAS_MYSQL OFF)
find_package(unofficial-libmariadb CONFIG QUIET)
if(TARGET unofficial::libmariadb::libmariadb)
    message(STATUS "MySQL (libmariadb) FOUND via find_package(unofficial-libmariadb CONFIG) — enabling TCV_HAS_MYSQL")
    set(TCV_HAS_MYSQL ON)
else()
    message(STATUS "MySQL (libmariadb) NOT found — TCV will run WITHOUT MySQL support")
    if(VCPKG_INSTALLED_DIR AND VCPKG_TARGET_TRIPLET)
        set(_ma_share "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/unofficial-libmariadb")
        if(EXISTS "${_ma_share}")
            message(STATUS "  share EXISTS: ${_ma_share}")
            message(STATUS "  but target unofficial::libmariadb::libmariadb not created — check Config file")
        else()
            message(STATUS "  share NOT FOUND at ${_ma_share} — vcpkg probably didn't install libmariadb")
        endif()
    endif()
endif()

if(TCV_HAS_PGSQL)
    target_link_libraries(TingCloudVerifier PRIVATE PostgreSQL::PostgreSQL)
    target_compile_definitions(TingCloudVerifier PRIVATE TCV_HAS_PGSQL=1)
endif()

if(TCV_HAS_MYSQL)
    target_link_libraries(TingCloudVerifier PRIVATE unofficial::libmariadb::libmariadb)
    target_compile_definitions(TingCloudVerifier PRIVATE TCV_HAS_MYSQL=1)
endif()
